//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.5.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace PizzaApp.HelperClasses
{
	/// <summary>Field Creation Class for entity OrdersListEntity</summary>
	public partial class OrdersListFields
	{
		/// <summary>Creates a new OrdersListEntity.CreatedAt field instance</summary>
		public static EntityField2 CreatedAt { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrdersListFieldIndex.CreatedAt); }}
		/// <summary>Creates a new OrdersListEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrdersListFieldIndex.Id); }}
		/// <summary>Creates a new OrdersListEntity.NumberOfPizzas field instance</summary>
		public static EntityField2 NumberOfPizzas { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrdersListFieldIndex.NumberOfPizzas); }}
		/// <summary>Creates a new OrdersListEntity.TotalPrice field instance</summary>
		public static EntityField2 TotalPrice { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrdersListFieldIndex.TotalPrice); }}
	}

	/// <summary>Field Creation Class for entity PizzaSideEntity</summary>
	public partial class PizzaSideFields
	{
		/// <summary>Creates a new PizzaSideEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PizzaSideFieldIndex.Id); }}
		/// <summary>Creates a new PizzaSideEntity.Price field instance</summary>
		public static EntityField2 Price { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PizzaSideFieldIndex.Price); }}
		/// <summary>Creates a new PizzaSideEntity.Sides field instance</summary>
		public static EntityField2 Sides { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PizzaSideFieldIndex.Sides); }}
	}

	/// <summary>Field Creation Class for entity PizzaSizeEntity</summary>
	public partial class PizzaSizeFields
	{
		/// <summary>Creates a new PizzaSizeEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PizzaSizeFieldIndex.Id); }}
		/// <summary>Creates a new PizzaSizeEntity.Price field instance</summary>
		public static EntityField2 Price { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PizzaSizeFieldIndex.Price); }}
		/// <summary>Creates a new PizzaSizeEntity.Sizes field instance</summary>
		public static EntityField2 Sizes { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PizzaSizeFieldIndex.Sizes); }}
	}

	/// <summary>Field Creation Class for entity PizzasListEntity</summary>
	public partial class PizzasListFields
	{
		/// <summary>Creates a new PizzasListEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PizzasListFieldIndex.Id); }}
		/// <summary>Creates a new PizzasListEntity.OrdersId field instance</summary>
		public static EntityField2 OrdersId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PizzasListFieldIndex.OrdersId); }}
		/// <summary>Creates a new PizzasListEntity.PricePerPizza field instance</summary>
		public static EntityField2 PricePerPizza { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PizzasListFieldIndex.PricePerPizza); }}
		/// <summary>Creates a new PizzasListEntity.Side field instance</summary>
		public static EntityField2 Side { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PizzasListFieldIndex.Side); }}
		/// <summary>Creates a new PizzasListEntity.Size field instance</summary>
		public static EntityField2 Size { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PizzasListFieldIndex.Size); }}
		/// <summary>Creates a new PizzasListEntity.Topping field instance</summary>
		public static EntityField2 Topping { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PizzasListFieldIndex.Topping); }}
	}

	/// <summary>Field Creation Class for entity PizzaToppingEntity</summary>
	public partial class PizzaToppingFields
	{
		/// <summary>Creates a new PizzaToppingEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PizzaToppingFieldIndex.Id); }}
		/// <summary>Creates a new PizzaToppingEntity.Price field instance</summary>
		public static EntityField2 Price { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PizzaToppingFieldIndex.Price); }}
		/// <summary>Creates a new PizzaToppingEntity.Toppings field instance</summary>
		public static EntityField2 Toppings { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PizzaToppingFieldIndex.Toppings); }}
	}
	

}